# Generated by Django 3.2.10 on 2022-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220208_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcourses',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
