# Generated by Django 3.2.10 on 2022-02-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartcourses_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
