# Generated by Django 3.2.10 on 2022-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(default='', null=True, upload_to='media/'),
        ),
    ]
